
---
- hosts: all
  become: true

  tasks:
      - name: Install aptitude using apt
        apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

      - name: Install required packages
        apt: name={{ item }} state=latest update_cache=yes
        loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

      - name: Add Docker GPG apt key
        apt_key: 
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add docker repository
        apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu xenial stable
            state: present

      - name: Install docker
        apt: name={{ item }} state=latest update_cache=yes
        loop: ['docker-ce','docker-ce-cli','containerd.io']

      - name: Install docker python module
        pip:
          name: docker

      - name: Install docker-compose
        get_url:
            url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: a+x
        tags:
            - compose
          
      - name: Add user '{{ ansible_ssh_user }}' to docker group
        user: 
            name: '{{ ansible_ssh_user }}'
            group: docker
            append: yes



















